spring:
  profiles:
    active: git
  cloud:
    config:
      server:
        encrypt:
          enabled: true
        git:
          uri: https://github.com/tekleayele/spring-cloud-config
#        native:
#          searchLocations: classpath:/
server:
  port: 8888

endpoints:
  restart:
    enabled: true
  refresh:
      enabled: true

encrypt:
  keyStore:
    location: classpath:/server.jks
    password: letmein
    alias: mytestkey
    secret: letmein

