version: '2.1'

services:
  service-provider-db:
    build: './excella-service-provider/src/main/resources/db/migration/'
    ports:
      - "5432:5432"

  config-server:
    build: './excella-config-server'
    ports:
      - "8888:8888"
    depends_on:
      service-provider-db:
        condition: service_started
    links:
      - service-provider-db

  eureka-server:
    build: './excella-eureka-server'
    ports:
      - "8761:8761"
    depends_on:
      config-server:
        condition: service_started

  service-provider:
    build: './excella-service-provider'
    ports:
      - "8181:8181"
    depends_on:
      eureka-server:
        condition: service_started
    links:
      - service-provider-db
      - config-server
      - eureka-server

  service-consumer:
    build: './excella-service-consumer'
    ports:
      - "8080:8080"
    depends_on:
      service-provider:
        condition: service_started
    links:
      - eureka-server
      - service-provider


