server:
  port: 8888

endpoints:
  restart:
    enabled: true
  refresh:
      enabled: true

eureka: #tells about the Eureka server details and its refresh time
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5