server:
  port: 8181    #default port where the service will be started

eureka:         #tells about the Eureka server details and its refresh time
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5

spring:
  application:
    name: excella-service-provider   #current service name to be used by the eureka server

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USER}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    flyway:
      baseline-on-migrate: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true

  security:
    ignored: /** # disable security check
    headers:
      frame: false

management:
  security:
    enabled: false  #disable the spring security on the management endpoints like /env, /refresh etc.

profiles:
  active: development

logging:
  level:
    demo: DEBUG
    org:
      hibernate:
        type: trace
        stat: debug