server:
  port: 8762    #default port where the service will be started

eureka: #tells about the Eureka server details and its refresh time
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5

zuul:
  ignoredServices: '*'
  routes:
    service1:
      path: /config-server/**
      url: http://config-server:8888

spring:
  application:
    name: excella-zuul-client-service   #current service name to be used by the eureka server

security:
  ignored: /** # disable security check

management:
  security:
    enabled: false  #disable the spring security on the management endpoints like /env, /refresh etc.

logging:
  level:
    demo: DEBUG