server:
  port: ${PORT:8761} # Indicate the default PORT where this service will be started

eureka:
  client:
    registerWithEureka: false   #telling the server not to register himself in the service registry
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0    #wait time for subsequent sync

security:
  ignored: /** # disable security check

management:
  security:
    enabled: false  #disable the spring security on the management endpoints like /env, /refresh etc.
